### ISSUE TITLE
[BUG] Latest Github Release Does Not Work

### ISSUE THREAD

**Issue by LinuxinaBit** [meditohq/medito-app#688]
**Describe the bug**
The apk from the latest Github release has a permanent network error and bugged dashboard.

**To Reproduce**

1. Go to  the latest release on Github
2. Download and install the apk
3. Open the app and see the bugged dashboard
4. Click the Packs tab and see the permanent network error

**Expected behavior**
The app should not have the error and not have a bugged dashboard screen. It should just work.

**Screenshots**
The error:
![Screenshot_20240329-232819](https://github.com/meditohq/medito-app/assets/105567407/5668e8a5-c062-4f02-9176-3322062a80de)
The broken dashboard:
![Screenshot_20240329-232813](https://github.com/meditohq/medito-app/assets/105567407/de5a939b-b95f-448a-a0f0-f982eb018e3f)

**Smartphone (please complete the following information):**

- Device: Motorola Moto G Power (2021)
- OS: Android 11
- Version: 2.0.48 

Version: 2.0.48 
 Device: {device_model: moto g power (2021), device_os: 11, device_platform: android} 
 Build Number: 20048 
 ReleaseMode: true EMPTY

**Additional context**
I do not have Google Play Services installed, though I don't believe this to be the issue.

**Comment by ChrisWin22** [comment]
From what I can tell, this is because of the lack of Google Play Service. The app used to use Firebase Analytics until Dec 2023 when a fix was merged. However, there is an open issue saying the release flow is broken so that fix hasn't been built into an apk on github yet. The version on Google Play Store currently works if you don't have Play Services. I'm not a dev on the project but I have the same issue and that is what I figured out from looking through the issues

**Comment by LinuxinaBit** [comment]
Just tried with Play Services temporarily enabled, still broken so I think it might be some kind of API thing? Not sure...

**Comment by ChrisWin22** [comment]
https://github.com/meditohq/medito-app/issues/642 make sure you are on the latest version (v3). v2 has been deprecated and no longer works

**Comment by LinuxinaBit** [comment]
I guess that must be the issue; the Github build is just out of date.
Hopefully it is fixed soon (a *lot* of people want to use it)

I'm going to leave this issue open for visability, but it's fine if a maintainer closes it.
